### PR TITLE
Show values of settings

### PR DESCRIPTION
**Pull request by ashishb**
As recommeneded in https://github.com/ashishb/adb-enhanced/issues/80

Show value of settings before and after the operation. For example,

```
$ python3 src/main.py show-taps on
Show user taps state changed from "off" -> "on"
$ python3 src/main.py show-taps on
Show user taps state unchanged (on)
$ python3 src/main.py show-taps off
Show user taps state changed from "on" -> "off"
```

I have implemented it for the following settings.
1. adbe [options] mobile-data (on | off)
2. adbe [options] battery saver (on | off) - done
3. adbe [options] mobile-data saver (on | off)
4. adbe [options] dont-keep-activities (on | off)
5. adbe [options] stay-awake-while-charging (on | off)
6. adbe [options] show-taps (on | off)

I have not yet implemented it for the following settings
1. adbe [options] gfx (on | off | lines)
2. adbe [options] overdraw (on | off | deut)
3. adbe [options] doze (on | off)
4. adbe [options] rtl (on | off)
5. adbe [options] animations (on | off)

### CODE REVIEW

**Comment by ubaierbhat** [comment]
```
$ python3 src/main.py show-taps 
Show-taps is currently -> "on"
$ python3 src/main.py show-taps on
Show user taps state unchanged (on)
$ python3 src/main.py show-taps off
Show user taps state changed from "on" -> "off"
```

**Comment by ashishb** [comment]
> What do you think about making (on|off) optional in order to know the current state? e.g

Interesting. How about `get show-taps` instead? I am a bit concerned that someone doing `show-tap (on|off)` might forget to add `on|off` and end up executing the wrong command.

**Comment by ubaierbhat** [comment]
I think it is better to keep it simple and avoid adding one more argument. I think `get ...` will be more confusing because if `get` is to read then `put` or `set` will be to write.

**Comment by ashishb** [comment]
That's a good point. I will make the change (unless you would like to send a PR).

**Comment by ubaierbhat** [comment]
Would have liked to send a PR but might not get time for next couple of weeks.

**Comment by ashishb** [comment]
> Would have liked to send a PR but might not get time for next couple of weeks.

I can wait :)
I would love more external contribution.

**Pull request merged**
